// Runtime functions linked with Cranelift-generated object files.
#![allow(dead_code)]
// The `extern "C"` ABI exports take raw pointers from Cranelift-generated code
// and dereference them; they are the unsafe FFI boundary by design, so
// `not_unsafe_ptr_arg_deref` (which wants `unsafe fn`, incompatible with the
// exported C symbol contract) is allowed crate-wide.
#![allow(clippy::not_unsafe_ptr_arg_deref)]
// FFI-boundary code casts raw pointers explicitly to document intent even when
// the source and target type already match; allow the resulting no-op casts.
#![allow(clippy::unnecessary_cast)]
// Some f64 formatting tests use `3.14` as a sample value, not an approximation
// of pi; the lint is a false positive there.
#![allow(clippy::approx_constant)]

pub mod args;
pub mod array;
pub mod async_frame;
pub mod async_mutex;
pub mod atomic;
pub mod blocking;
pub mod cancellation;
pub mod channel;
pub mod executor;
pub mod fs;
pub mod future;
pub mod gc;
pub mod gc_mark_queue;
pub mod lock;
pub mod lock_wait;
pub mod map;
pub mod math;
pub mod net;
pub mod netpoll;
pub mod object;
pub mod observability;
pub mod panic;
pub mod panic_context;
pub mod parallel;
pub mod preempt;
pub mod print;
pub mod reference_debug;
pub mod scheduler;
pub mod stack_trace;
pub mod string;
pub mod sync;
pub mod task;
pub mod task_state;
pub mod timer;
pub(crate) mod timer_queue;
pub mod trace;
pub mod wait_queue;

use std::ffi::c_char;

#[cfg(not(test))]
unsafe extern "C" {
    fn willow_user_main();
    // Generated by the compiler: initializes all `static` properties before
    // `main` (willow-qsqf). Always emitted (a no-op when there are none).
    fn __willow_static_init();
}

#[cfg(test)]
#[unsafe(no_mangle)]
unsafe extern "C" fn willow_user_main() {}

#[cfg(test)]
#[unsafe(no_mangle)]
unsafe extern "C" fn __willow_static_init() {}

#[unsafe(no_mangle)]
pub extern "C" fn runtime_start(argc: i32, argv: *mut *mut c_char) {
    args::willow_runtime_store_args(argc, argv);
    gc::willow_gc_init();
    // Synchronous top-level code owns a standalone execution context. Task
    // polls temporarily replace this TLS cache with their task-owned context;
    // the scheduler restores it when a nested/outer drive returns.
    let sync_panic_context = std::sync::Arc::new(panic_context::PanicContext::new(0));
    let previous_panic_context = panic_context::replace_current_context(Some(sync_panic_context));
    // Static properties are initialized once, after the GC is ready and before
    // user `main` runs (willow-qsqf §11).
    unsafe { __willow_static_init() };
    unsafe { willow_user_main() };
    panic_context::replace_current_context(previous_panic_context);
}

#[cfg(not(test))]
#[unsafe(no_mangle)]
pub extern "C" fn main(argc: i32, argv: *mut *mut c_char) -> i32 {
    runtime_start(argc, argv);
    0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn runtime_start_stores_arguments_before_user_main() {
        let _guard = gc::runtime_test_guard();
        let program = std::ffi::CString::new("willow-test").unwrap();
        let first = std::ffi::CString::new("one").unwrap();
        let second = std::ffi::CString::new("two").unwrap();
        let mut argv = vec![
            program.as_ptr() as *mut c_char,
            first.as_ptr() as *mut c_char,
            second.as_ptr() as *mut c_char,
        ];

        runtime_start(argv.len() as i32, argv.as_mut_ptr());

        assert_eq!(args::willow_runtime_args_len(), 2);
        let arg0 = args::willow_runtime_arg(0);
        assert!(!arg0.is_null());
        assert_eq!(unsafe { string::willow_string_as_str(arg0) }, "one");
    }
}
